console.log("Questão 1)");
console.log("O arquivo ex1.js está funcionando");
console.log("--------------------------------------------------------");
console.log("Questão 2)");
var nome = "Wilderlan";
var anoNascimento = 1991;
var anoAtual = 2024;
var idade = anoAtual-anoNascimento;
console.log("Olá, eu me chamo "+nome+", tenho "+idade+" anos e estou estudando Javascript.");
console.log("--------------------------------------------------------");
console.log("Questão 3)");
var Aluno = "João"
var matricula = "321654";
var prova1 = 9.8;
var prova2 = 8;
var media = (prova1+prova2)/2;
console.log("O aluno "+Aluno+", matrícula "+matricula+", obteve a média final "+media+".");
console.log("--------------------------------------------------------");
console.log("Questão 4)");
var telefone = "945787466";
console.log("Resultado do teste:"+(telefone.length == 9));
console.log("--------------------------------------------------------");
console.log("Questão 5)");
console.log(Math.pow(32,6));
console.log("--------------------------------------------------------");
console.log("Questão 6)");
console.log("C = Não pode usar devido typeof ser uma key word do Javascript");
console.log("D = Não pode usar o - em nome de variáveis.");
console.log("F = Não pode usar número no primeiro caractere.");
console.log("G = Não pode usar devido possuir espaço.");
console.log("--------------------------------------------------------");
console.log("Questão 7)");
console.log("1º Irá ocorrer o processo de concatenação e não uma somatória deverido serem string");
console.log("2º Irá ocorrer primeiro o calculo que está em parenteses e depois irá fazer a divisão e em seguida irá somar o dois. Resultado 4");
console.log("3º Irá retornar a informação de undefined");
console.log("4º Irá retornar a informação de null");
console.log("5º Irá retornar a informação do tipo undefined");
console.log("5º Irá retornar a informação do tipo object");
console.log("--------------------------------------------------------");
console.log("Questão 8)");
console.log("1º Será efetuado uma validação e o resultado é um boleano de false");
console.log("2º Será efetuado uma validação e o resultado é um boleano de true");
console.log("3º Será efetuado uma validação e o resultado é um boleano de true devido a expressão ==");
console.log("4º Será efetuado uma validação e o resultado é um boleano de false devido a expressão ==");
console.log("5º Será efetuado uma validação e o resultado é a informação do tipo boolean");
console.log("6º Será efetuado uma validação e o resultado é a informação do tipo boolean");